---
- name: copy files
  hosts: all 
  become: true
  become_user: root
  tasks:
    - name: copy files amonng different folder
      copy:
       src: "/tmp/ansible/content/test01.txt"
       dest: "/tmp/"
     
       

