---
- name: My first play
  hosts: all
  become_user: root
  become: true
  tasks:
   - name: Ping my hosts
     ansible.builtin.ping:

   - name: Print message
     ansible.builtin.debug:
       msg: welcome to Ansible
