---
- name: creating multiple files and direcotry
  hosts: all
  become_user: root
  become: true
  tasks:
    - name: creating directory
      file:
        path: "/tmp/ansible/"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: create multiple files
      file:
        path: "/tmp/ansible/{{ item }}"
        state: touch
        owner: root
        group: root
        mode: '0700'

      with_items:
      - test01.txt
      - test02.txt
      - test03.txt
      - test04.txt
        

